### ISSUE TITLE
TypeError: list indices must be integers or slices, not str

### ISSUE THREAD

**Issue by RayZ1212** [Enderlogic/MMHC-Python#3]
Traceback (most recent call last):
  File "C:/Users/RayZ/Desktop/MMHC-Python-master/BN_structure_learning.py", line 48, in <module>
    compare_result = compare(cpdag(true_dag), cpdag(dag))
  File "C:\Users\RayZ\Desktop\MMHC-Python-master\lib\accessory.py", line 6, in cpdag
    if (len(cpdag[var]['par']) > 1):
TypeError: list indices must be integers or slices, not str

**Comment by Enderlogic** [comment]
Thank you for reporting this bug. I have removed this function in the new version and use the cpdag function provided by bnlearn package. Hope the code can work now.
